{
  "openapi": "3.0.0",
  "info": {
    "title": "API Autentication Users",
    "descriptions": "Serviço com foco em validações e gerenciamente de permissões de usuarios",
    "contact": {
      "email": "nivaldeir-silva@hotmail.com"
    }
  },
  "paths": {
    "/auth/sign-in": {
      "post": {
        "summary": "Autenticação de usuario",
        "descriptions": "Usuario pode escolher, autenticar pelo email ou password",
        "tags": ["Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "Not Found",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Error"
                  }
                }
              }
            },
            "200": {
              "description": "OK",
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthResponse200"
                }
              }
            }
          }
        }
      }
    },
    "/auth/recovery": {
      "post": {
        "summary": "Solicitação para redefinir a senha",
        "descriptions": "Solicitação para redefinir a senha",
        "tags": ["Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "Not Found",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Error"
                  }
                }
              }
            },
            "200": {
              "description": "OK"
            }
          }
        }
      }
    },
    "/auth/recovery/{token}": {
      "post": {
        "summary": "Redefinir a senha",
        "descriptions": "Redefinir a senha",
        "tags": ["Auth"],
        "parameters": [
          {
            "name": "token",
            "in": "path",
            "description": "token do usuario",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "empasswordail": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "Not Found",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Error"
                  }
                }
              }
            },
            "200": {
              "description": "OK"
            }
          }
        }
      }
    },
    "/auth/report/{id}": {
      "get": {
        "summary": "Buscando historico de autenticação do usuario",
        "tags": ["Auth"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuario",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  },
                  "data": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "userEmail": {
                          "type": "string"
                        },
                        "idAddress": {
                          "type": "string"
                        },
                        "successful": {
                          "type": "boolean"
                        },
                        "details": {
                          "type": "string"
                        },
                        "createdAt": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "userAuthenticationId": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "userEmail",
                        "idAddress",
                        "successful",
                        "details",
                        "createdAt",
                        "userAuthenticationId"
                      ]
                    }
                  }
                },
                "required": ["message", "data"]
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/user": {
      "post": {
        "summary": "Cadastro de usuario",
        "descriptions": "",
        "tags": ["User"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "email": "test@test.com.br",
                    "username": "test",
                    "password": "test",
                    "id": "optional"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "409": {
            "description": "Já existe informação com esse...",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Busca de usuario",
        "descriptions": "",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["User"],
        "responses": {
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/UserArray"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}": {
      "get": {
        "descriptions": "Busca de usuario pelo ID",
        "summary": "Busca de usuario pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["User"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuario",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "put": {
        "descriptions": "Atualizando um usuario pelo ID",
        "summary": "Atualizando um usuario pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["User"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do usuario",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "username": "optional",
                    "password": "optional"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "delete": {
        "descriptions": "Desativando um usuario pelo ID",
        "summary": "Desativando um usuario pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["User"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do usuario",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}/deleting-permission": {
      "put": {
        "descriptions": "Remoção permissão do usuario pelo ID",
        "summary": "Remoção permissão do usuario pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["User"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuario",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "user": {
                  "value": {
                    "permission": "create_user"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}/adding-permission": {
      "put": {
        "descriptions": "Adicionando permissão do usuario pelo ID",
        "summary": "Adicionando permissão do usuario pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["User"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuario",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "user": {
                  "value": {
                    "permission": "create_user"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/permission": {
      "post": {
        "summary": "Cadastro de permissões",
        "descriptions": "",
        "tags": ["Permission"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Permission"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "create_user"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "409": {
            "description": "Já existe informação com esse...",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Permission"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Busca de Permissões",
        "descriptions": "",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Permission"],
        "responses": {
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/PermissionArray"
                }
              }
            }
          }
        }
      }
    },
    "/permission/{id}": {
      "get": {
        "descriptions": "Busca de permissão pelo ID",
        "summary": "Busca de permissão pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Permission"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do permissão",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Permission"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "put": {
        "descriptions": "Atualizando um permissão pelo ID",
        "summary": "Atualizando um permissão pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Permission"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do permissao",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "user": {
                  "value": {
                    "name": "create_user"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Permission"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "descriptions": "Deletando uma permissão pelo ID",
        "summary": "Deletando um permissão pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Permission"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID da permissão",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/role": {
      "post": {
        "summary": "Cadastro de cargo",
        "descriptions": "",
        "tags": ["Role"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Role"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "admin"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "409": {
            "description": "Já existe informação com esse...",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Busca de Roles",
        "descriptions": "",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Role"],
        "responses": {
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/RoleArray"
                }
              }
            }
          }
        }
      }
    },
    "/role/{id}": {
      "get": {
        "descriptions": "Busca de role pelo ID",
        "summary": "Busca de role pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Role"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuario",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Role"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "put": {
        "descriptions": "Atualizando um role pelo ID",
        "summary": "Atualizando um role pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Role"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do role",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "user": {
                  "value": {
                    "name": "Admin"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Role"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "delete": {
        "descriptions": "Deletando um usuario pelo ID",
        "summary": "Deletando um usuario pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Role"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID da role",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/role/{id}/adding-permission": {
      "put": {
        "descriptions": "Adicionando uma permissão do cargo pelo IDD",
        "summary": "Adicionando uma permissão do cargo pelo IDD",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Role"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do role",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "user": {
                  "value": {
                    "permission": "create_user"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Role"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/role/{id}/deleting-permission": {
      "put": {
        "descriptions": "Deletando uma permissão do cargo pelo ID",
        "summary": "Deletando uma permissão do cargo pelo ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Role"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do role",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "user": {
                  "value": {
                    "permission": "create_user"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Role"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserArray": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "enabled": {
                  "type": "boolean"
                },
                "id": {
                  "type": "string"
                },
                "roleId": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              },
              "required": ["email", "enabled", "id", "roleId", "username"]
            }
          }
        },
        "required": ["message", "data"]
      },
      "User": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string"
              },
              "enabled": {
                "type": "boolean"
              },
              "id": {
                "type": "string"
              },
              "roleId": {
                "type": "string"
              },
              "username": {
                "type": "string"
              },
              "password": {
                "type": "string"
              },
              "salt": {
                "type": "string"
              }
            }
          }
        },
        "Role": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "Permission": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "Auth": {
          "type": "object",
          "properties": {
            "password": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "username": {
              "type": "string"
            }
          }
        },
        "ResponseError": {
          "type": "object",
          "properties": {
            "error": {
              "type": "boolean"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "RoleArray": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "boolean"
                },
                "permission": {
                  "type": "array",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "required": ["message", "data"]
      },
      "Role": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "boolean"
              },
              "permission": {
                "type": "array",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "Role": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "Permission": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "Auth": {
          "type": "object",
          "properties": {
            "password": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "username": {
              "type": "string"
            }
          }
        },
        "ResponseError": {
          "type": "object",
          "properties": {
            "error": {
              "type": "boolean"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "PermissionArray": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "boolean"
                }
              }
            }
          }
        },
        "required": ["message", "data"]
      },
      "Permission": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "boolean"
              }
            }
          }
        },
        "Role": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "Permission": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "Auth": {
          "type": "object",
          "properties": {
            "password": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "username": {
              "type": "string"
            }
          }
        },
        "ResponseError": {
          "type": "object",
          "properties": {
            "error": {
              "type": "boolean"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "AuthResponse200": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "token": {
                "type": "string"
              }
            }
          }
        },
        "Role": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "Permission": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "Auth": {
          "type": "object",
          "properties": {
            "password": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "username": {
              "type": "string"
            }
          }
        },
        "ResponseError": {
          "type": "object",
          "properties": {
            "error": {
              "type": "boolean"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "error": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "securitySchemes": {
        "bearerAuth": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT"
        }
      }
    }
  }
}
